### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by opensprinklershop** [jandrassy/EthernetENC#1]
Howto use ping with EthernetENC? 
I mean send icmp requests

**Comment by jandrassy** [comment]
sorry for the delay.
uIP supports ICMP, but it is not implemented in Ethernet. it should be possible. 
I will try to implement it later this week like this
https://www.arduino.cc/en/Reference/WiFiNINAPing

**Comment by jandrassy** [comment]
so uIP only supports replaying to ping, it doesn't support recieve of replay to ping. (sending ping is simple)
I did find icmp enhancement of uIP only for IPv6. it was written by Adam Dunkels the author of uIP. it started as implementation for icmp6 replay and then it was enhanced for sending a ping request. Maybe I could add IPv4 ICMP the same way.

**Comment by opensprinklershop** [comment]
Maybe this implementation could help? It's for the W5100:
https://github.com/BlakeFoster/Arduino-Ping

**Comment by jandrassy** [comment]
> Maybe this implementation could help? It's for the W5100:
> https://github.com/BlakeFoster/Arduino-Ping

no. on W5c00 the TCP/IP stack is in the chip. here I have to enhance ICMP support to the 20 years old uIP library, which is merged in this library

**Comment by opensprinklershop** [comment]
Or this?
https://github.com/ValentinBELYN/icmplib/tree/master/icmplib
