### ISSUE TITLE
ethernetENC http post request take too much time to execute on esp23

### ISSUE THREAD

**Issue by sdrshnptl** [jandrassy/EthernetENC#12]
Hello All,
I've connected enc28760 with esp32 to push data over local server using post method.
while testing with postman tool, it shows some 100~180ms to complete post request.
while my esp32 module taking around ~2200ms.

```
String postData = "red=123&green=345&blue=123&white=123";
httpClient.post("/rgbw/val?", "application/x-www-form-urlencoded", postData);
```

Any help would be appreciated!

**Comment by jandrassy** [comment]
I am sure the problem is not in the EthernetENC library. 
do you read the result?
are you sure it goues over EthernetClient and not WiFiClient?
