### ISSUE TITLE
The ethernet.begin(mac) doesn't work

### ISSUE THREAD

**Issue by Daescobarh9415** [jandrassy/EthernetENC#18]
I've just tried to use the EthernetENC library with the WebClient example, but the program it stays in an infinite loop in ethernet.begin (mac); I checked and saw that it does not come out of a while in Enc28J60Network.cpp line 263, because the function readReg(EIR) always return 0x00. 

I am using a mkr1010 and enc28j60

Does anyone know what could be wrong?

**Comment by jandrassy** [comment]
the SPI communication with the module doesn't work. how did you wire it?

**Comment by Daescobarh9415** [comment]
> the SPI communication with the module doesn't work. how did you wire it?
> `Ethernet.hardwareStatus`?

Yes, it is detecting it, it returns 10.
At this moment it is working for me but only with static IP I have managed to do some tests; but by DHCP it has not been possible; and for my application it is better to do it by DHCP

**Comment by jandrassy** [comment]
ok. If the Ethernet.linkStatus() is invoked too soon, it may return LinkOFF.
for DHCP see https://github.com/jandrassy/EthernetENC/issues/9

**Comment by Daescobarh9415** [comment]
> ok. If the Ethernet.linkStatus() is invoked too soon, it may return LinkOFF.
> for DHCP see #9
> and https://github.com/jandrassy/EthernetENC/wiki/Limitations

Thank you so much, the problem was solved adding 
`|ERXFCON_BCEN`
in
`writeReg(ERXFCON, ERXFCON_UCEN|ERXFCON_CRCEN|ERXFCON_PMEN|ERXFCON_BCEN);`
 as indicated in [#9](https://github.com/jandrassy/EthernetENC/issues/9)

**Comment by RaysoftTechnologiesInc** [comment]
Hi @Daescobarh9415,

I am having an issue in which i am not even able to get the ENC module to work via DHCP, i have tried to follow what you guys discussed here, but no luck so far, would you be able to share with me the files you edited Ijust want to check them out, or maybe explain exactly where i go edit in the code.

I am trying to interface the ENC module with a Nucleo using mbed. I will greatly appreciate your assistance.
