### ISSUE TITLE
Ping response

### ISSUE THREAD

**Issue by pablo-eg** [jandrassy/EthernetENC#19]
Hi!
 
Sorry if the question is stupid, is there any example of how to implement ping response?

Thanks in advance

**Comment by jandrassy** [comment]
the uIP TCP/IP stack used in EthernetENC library responses to ping

**Comment by pablo-eg** [comment]
Do you mean that if the linkStatus is LinkON I should be able to ping my embedded system?

**Comment by jandrassy** [comment]
> Do you mean that if the linkStatus is LinkON I should be able to ping my embedded system?

IP must be assigned too
