### ISSUE TITLE
Init without ENC28J60 Module causes resets

### ISSUE THREAD

**Issue by opensprinklershop** [jandrassy/EthernetENC#2]
Hi,
the OpenSprinkler 3 project uses an OPTIONAL ENC28J60 Module for the ESP8266. So when the module is missing, we have an endless boot loop.
Here is my patch for your library to fix this.

[EthernetEncInitFix.zip](https://github.com/jandrassy/EthernetENC/files/5362163/EthernetEncInitFix.zip)

**Comment by jandrassy** [comment]
it is not EthernetENC code you have there. it is from UIPEthernet

with EthernetENC git version you can run
```
if (Ethernet.hardwareStatus() == EthernetNoHardware) 
```
before `begin()` to check if the module is present.
