### ISSUE TITLE
ENC28J60 and SD card module on ESP32

### ISSUE THREAD

**Issue by Ganesh-Shanbhag-face** [jandrassy/EthernetENC#21]
Hi, I am using ENC28J60 Ethernet module (SPI) and SD Card module (SPI) with ESP32 as I need wired networking on ESP32. Ethernet Module and SD Card module are using different CS pin. Ethernet Module when connected to ESP32 without connecting the SD Card module will get the IP from DHCP. But when connected with SD Card module won't work but the SD Card module works alone. What may be the problem?

And when used Ethernet Module alone although it gets IP from DHCP is not connecting to MQTT (Hive MQ Public Client). What may be the problem?

**Comment by jandrassy** [comment]
I don't recommend to use this library with the esp32. esp32 as much better options for Ethernet.

The problem could be SPI speed. Try to set lower speed than the 20MHz here
https://github.com/jandrassy/EthernetENC/blob/c735fd4cf6821a166ef6b36dd56bd861ba61c400/src/utility/Enc28J60Network.cpp#L39

**Comment by Ganesh-Shanbhag-face** [comment]
@jandrassy I tried with that but it did not work. Can you suggest any module which works with this library on ESP32?

**Comment by jandrassy** [comment]
do you use a 3.3 V powered module or a module with 5 V powering and a level shifter chip?

**Comment by Ganesh-Shanbhag-face** [comment]
Ethernet module is working on 3.3V and SD Card module with 5V with inbuilt 3.3V regulator. So, literally both are working on 3.3V.

**Comment by jandrassy** [comment]
but then the SD card module should convert 5 V SPI to 3.3 V SPI and converts 3.3 V SPI to ?.? V SPI

**Comment by Ganesh-Shanbhag-face** [comment]
No for SD Card module there is inbuilt regulator which will convert it into 3.3V and supplies to the controller/buffer as well as to the SD Card. Since the controller/buffer and SD card are powered by 3.3V there levels are 3.3V compatible.

**Comment by jandrassy** [comment]
which side of the 'buffer'?

**Comment by Ganesh-Shanbhag-face** [comment]
SD Card module is using LVC125A.

**Comment by jandrassy** [comment]
> LVC125A

then it is OK

**Comment by simogaspa84** [comment]
> I don't recommend to use this library with the esp32. esp32 as much better options for Ethernet.
> 
> The problem could be SPI speed. Try to set lower speed than the 20MHz here
> 
> https://github.com/jandrassy/EthernetENC/blob/c735fd4cf6821a166ef6b36dd56bd861ba61c400/src/utility/Enc28J60Network.cpp#L39

Does it work this library with ESP32 ? Thanks a lot

**Comment by jandrassy** [comment]
> Does it work this library with ESP32 ? Thanks a lot

It does work even it is not a recommended Ethernet solution for esp32

**Comment by jandrassy** [comment]
> Thanks a lot for the quick reply... Can I ask you why it is not recommended ? Thanks a lot

esp32 has LwIP TCP/IP stack which handles WiFi, SoftAP and the esp32 Ethernet peripheral.
EthernetENC uses uIP TCP/IP stack and was designed for small MCU with a small RAM.
