### ISSUE TITLE
'class EthernetServer' has no member named 'write'

### ISSUE THREAD

**Issue by matkor** [jandrassy/EthernetENC#22]
I am trying to replace UIPEthernet with EthernetENC for my tiny MySensors project but compilation fails with
```
/home/matkor/Arduino/libraries/MySensors/core/MyGatewayTransportEthernet.cpp: In function 'bool gatewayTransportSend(MyMessage&)':
/home/matkor/Arduino/libraries/MySensors/core/MyGatewayTransportEthernet.cpp:297:27: error: 'class EthernetServer' has no member named 'write'
  nbytes = _ethernetServer.write(_ethernetMessage);
                           ^~~~~
Using library EthernetENC at version 2.0.2 in folder: /home/matkor/Arduino/libraries/EthernetENC 
Using library MySensors at version 2.3.2 in folder: /home/matkor/Arduino/libraries/MySensors 
```

Is it my error, MySensors or EthernetENC just lacks that method now?
Regards, TIA

**Comment by ondras12345** [comment]
https://github.com/jandrassy/EthernetENC/wiki/Examples
> In PagerServer, ChatServer and DhcpChatServer examples please use EthernetServerPrint server(23). EthernetServer in EthernetENC library doesn't support writing to all clients because it takes flash and RAM and has little use. This function is only in EthernetServerPrint class.

**Comment by jandrassy** [comment]
and https://github.com/jandrassy/EthernetENC/wiki/Limitations
