### ISSUE TITLE
Static code check 

### ISSUE THREAD

**Issue by simogaspa84** [jandrassy/EthernetENC#23]
Hi.. 

Running the analysis I got this info from Cppcheck 2.6 

![image](https://user-images.githubusercontent.com/12874425/153064549-ddc32274-2150-4d7c-9e76-f97de2ed2e98.png)

``

UIPUDP::beginPacket(IPAddress ip, uint16_t port)
{
  UIPEthernetClass::tick();
  if ((ip[0] || ip[1] || ip[2] || ip[3]) && port)
    {
      uip_ipaddr_t ripaddr;
      uip_ip_addr(&ripaddr, ip);

Maybe it is a false positive but better to check... 

I hope it helps

Simone

**Comment by jandrassy** [comment]
https://trac.cppcheck.net/ticket/9554
