### ISSUE TITLE
Not compiling: 'class EthernetServer' has no member named 'write'

### ISSUE THREAD

**Issue by byteptr** [jandrassy/EthernetENC#4]
I take this source [https://www.arduino.cc/en/Tutorial/LibraryExamples/ChatServer](url)
Then following these notes seems not compile: 
[https://github.com/jandrassy/EthernetENC/wiki/Examples](url)

"Only change #include <Ethernet.h> to #include <EthernetENC.h>." <-- I did, and this is OK
"In ChatServer and DhcpChatServer examples please use EthernetServerWrite server(23)" <-- I replaced the line "EthernetServer server(23);" with "EthernetServerWrite server(23);" but I have the following error: 'EthernetServerWrite' does not name a type; did you mean 'EthernetServerPrint'?

Can you provide a modified example compiling please ?

**Comment by jandrassy** [comment]
https://github.com/jandrassy/EthernetENC/wiki/Examples

**Comment by jandrassy** [comment]
fixed in Wiki
