### ISSUE TITLE
no function `ethernet.MACAddress()` to drop-in replace ethernet.h

### ISSUE THREAD

**Issue by cyberboy666** [JAndrassy/EthernetENC#55]
i am trying to use this library as a drop-in replacement for the standard [arduino ethernet library](https://github.com/arduino-libraries/Ethernet) inside the this [artnet library](https://github.com/hideakitai/ArtNet)

everything works perfectly - except for [this](https://github.com/hideakitai/ArtNet/blob/main/Artnet/ArtnetCommon.h#L624) line in artnet code where it calls:

```
#ifndef ESP8266
            Ethernet.MACAddress(mac);
#endif
```

which doesnt exist in the EthernetENC version. 

ultimately i want to add support for EthernetENC to the artnet library - although its not clear to me if i should solve this by modifying the logic in artnet or adding this function to this library ? is this meant to be used as drop-in like this ? is it possible to add this function here or a reason why its not here ? 

thanks for your help!

**Comment by JAndrassy** [comment]
done

**Comment by cyberboy666** [comment]
tested for my use case and it works! thanks again
